Hanaro-JSON/LifeOnHana_BE

- src/main/java/com/example/lifeonhana/ApiResponse.java
- src/main/java/com/example/lifeonhana/global/exception/BadRequestException.java
- src/main/java/com/example/lifeonhana/global/exception/BaseException.java
- src/main/java/com/example/lifeonhana/global/exception/ForbiddenException.java
- src/main/java/com/example/lifeonhana/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/lifeonhana/global/exception/NotFoundException.java
- src/main/java/com/example/lifeonhana/global/exception/UnauthorizedException.java
>  #1 , #2 
> global exception handler 구현
> `feature/exception`
> 문제 있으면 알려주세요! 
> api 명세 작성 후 이슈 작성
> [feat] 🧚🏻‍♀️ global exception 생성 feature/exception

- .gitignore
- src/main/java/com/example/lifeonhana/entity/Account.java
- src/main/java/com/example/lifeonhana/entity/Article.java
- src/main/java/com/example/lifeonhana/entity/ArticleDictionary.java
- src/main/java/com/example/lifeonhana/entity/ArticleLike.java
- src/main/java/com/example/lifeonhana/entity/ArticleProduct.java
- src/main/java/com/example/lifeonhana/entity/History.java
- src/main/java/com/example/lifeonhana/entity/LumpSum.java
- src/main/java/com/example/lifeonhana/entity/Product.java
- src/main/java/com/example/lifeonhana/entity/ProductLike.java
- src/main/java/com/example/lifeonhana/entity/User.java
- src/main/java/com/example/lifeonhana/entity/Wallet.java
- src/main/resources/application.yml
> #13 
> entity 수정
> JSON-118--fix/entity
> entity 랑 erd 다른점 있는지 확인필요
> 로그인
> [fix] 🐢 entity 수정 #13

- build.gradle
- src/main/java/com/example/lifeonhana/ApiResponse.java
- src/main/java/com/example/lifeonhana/controller/AuthController.java
- src/main/java/com/example/lifeonhana/global/exception/BadRequestException.java
- src/main/java/com/example/lifeonhana/global/exception/BaseException.java
- src/main/java/com/example/lifeonhana/global/exception/ForbiddenException.java
- src/main/java/com/example/lifeonhana/global/exception/NotFoundException.java
- src/main/java/com/example/lifeonhana/global/exception/UnauthorizedException.java
- src/main/resources/application.yml
- #20
- swagger 초기설정 추가
- exception 상태코드 출력부분 수정
- `feature/wallet`
- 하나지갑 관련 api 개발 착수
> [feat] 🧚🏻‍♀️ Swagger 초기설정 추가

- src/main/java/com/example/lifeonhana/global/util/PasswordEncoderUtil.java
> ex) #22
> 로그인 암호화 오류 수정
> JSON-119--fix/login
> 다음 작업 계획 간단히
> [fix] 🐢 로그인 오류 수정 #22

- build.gradle
- src/main/java/com/example/lifeonhana/ApiResult.java
- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- src/main/java/com/example/lifeonhana/config/SwaggerConfig.java
- src/main/java/com/example/lifeonhana/controller/AuthController.java
- src/main/java/com/example/lifeonhana/entity/User.java
- src/main/java/com/example/lifeonhana/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/lifeonhana/repository/UserRepository.java
- src/main/resources/application.yml
> #20
> jacoco, swagger 추가, spring boot 버전낮춤 3.4.1 -> 3.3.5, user entity 에서 provider 삭제
> JSON-123--feature/jacoco&swagger
> 다음 작업 계획 간단히
> [feat] 🐢 jacoco, swagger 추가 #20

- src/main/java/com/example/lifeonhana/filter/JwtAuthenticationFilter.java
- src/main/java/com/example/lifeonhana/service/AuthService.java
- src/main/java/com/example/lifeonhana/service/JwtService.java
> ex) #26 
> jwtservice extractemail 이름 변경 
> JSON-123--feature/jacoco&swagger
> [fix] jwtservice extractemail 이름 변경 #26

- build.gradle
- src/main/java/com/example/lifeonhana/dto/AuthRequestDTO.java
- src/main/java/com/example/lifeonhana/dto/RefreshTokenRequestDTO.java
- src/main/java/com/example/lifeonhana/filter/JwtAuthenticationFilter.java
- src/test/java/com/example/lifeonhana/auth/AuthIntegrationTest.java
- src/test/java/com/example/lifeonhana/auth/AuthServiceTest.java
- src/test/java/com/example/lifeonhana/jwt/JwtAuthenticationFilterTest.java
- src/test/java/com/example/lifeonhana/jwt/JwtServiceTest.java
- src/test/java/com/example/lifeonhana/redis/RedisServiceTest.java
> #28
> 로그인 테스트 코드 작성
> JSON-148--test/login
> 다음 작업 계획 간단히
> [test] 🐢 로그인 테스트 코드 작성 #28

- src/main/java/com/example/lifeonhana/LifeonhanaApplication.java
- src/main/java/com/example/lifeonhana/batch/RedisToDatabaseSynchronizer.java
- src/main/java/com/example/lifeonhana/controller/ArticleLikeController.java
- src/main/java/com/example/lifeonhana/dto/response/LikeResponseDto.java
- src/main/java/com/example/lifeonhana/entity/ArticleLike.java
- src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
- src/main/java/com/example/lifeonhana/repository/ArticleRepository.java
- src/main/java/com/example/lifeonhana/service/ArticleLikeService.java
> ex) #35 #36 
> 칼럼 좋아요 생성 && 취소 api
사용자의 좋아요 여부와 칼럼 당 좋아요 수 조회 api
> JSON-154--feature/account
> 좋아요 한 칼럼 목록 조회 api 구현
> [feat] 🦧 좋아요 관련 api

- src/main/java/com/example/lifeonhana/controller/AccountController.java
- src/main/java/com/example/lifeonhana/dto/response/SalaryAccountResponseDTO.java
- src/main/java/com/example/lifeonhana/repository/AccountRepository.java
- src/main/java/com/example/lifeonhana/service/AccountService.java
> ex) #47 
> 하나 월급 통장 잔액을 조회하는 API를 개발했습니다.
> JSON-161--feature/salary
> 다음 작업 계획 간단히
> [feat] 🦥 하나 월급 통장 잔액 조회

- src/main/java/com/example/lifeonhana/controller/UserController.java
- src/main/java/com/example/lifeonhana/dto/response/UserResponseDTO.java
- src/main/java/com/example/lifeonhana/service/UserService.java
> #49 
> 사용자 정보
> JSON-162--feature/userInfo
> 다음 작업 계획 간단히
> [feat] 🦥 사용자 정보 조회

- src/main/java/com/example/lifeonhana/controller/UserController.java
- src/main/java/com/example/lifeonhana/dto/response/MyDataResponseDTO.java
- src/main/java/com/example/lifeonhana/repository/HistoryRepository.java
- src/main/java/com/example/lifeonhana/service/UserService.java
>  #51 
> 마이데이터 조회 및 월 평균 지출 통계 조회
> JSON-163--feature/user-mydata
> 다음 작업 계획 간단히
> [feat] 🦥 마이데이터 조회

- src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
- src/main/java/com/example/lifeonhana/dto/request/LoanRecommendationRequest.java
- src/main/java/com/example/lifeonhana/dto/response/LoanProductResponse.java
- src/main/java/com/example/lifeonhana/repository/LoanProductRepository.java
- src/main/java/com/example/lifeonhana/service/ArticleService.java
- src/main/java/com/example/lifeonhana/service/FlaskService.java
- src/main/java/com/example/lifeonhana/service/LoanRecommendationService.java
> #41 
> anthropic api 기반 대출 사유, 금액, 사용자의 마이데이터를 이용해 대출 상품들을 추천한 목록을 조회하는 api
> JSON-158-feature/anthropicLoanProducts
> anthropic api 기반 상품 기대효과 시작하기
> [feat] 🦧 anthropic api 기반 대출 상품 추천 api

- src/main/java/com/example/lifeonhana/controller/UserController.java
- src/main/java/com/example/lifeonhana/dto/response/UserNicknameResponseDTO.java
- src/main/java/com/example/lifeonhana/entity/enums/ArticleCategory.java
- src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
- src/main/java/com/example/lifeonhana/service/UserService.java
> #60 
> 사용자 취향 문구를 조회합니다.
> JSON-167--feture/user-preference
> 다음 작업 계획 간단히
> [feat] 🦥 사용자 취향 문구 조회

- src/main/java/com/example/lifeonhana/controller/ArticleController.java
- src/main/java/com/example/lifeonhana/dto/response/ArticleListItemResponse.java
- src/main/java/com/example/lifeonhana/dto/response/ArticleListResponse.java
- src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
- src/main/java/com/example/lifeonhana/repository/ArticleRepository.java
- src/main/java/com/example/lifeonhana/service/ArticleService.java
> ex) #63 
> 칼럼 목록 조회 기능
> JSON-169--feature/articles
> 다음 작업 계획 간단히
> [feat] 🦥 칼럼 목록 조회

- src/main/java/com/example/lifeonhana/controller/AccountController.java
- src/main/java/com/example/lifeonhana/controller/ArticleController.java
- src/main/java/com/example/lifeonhana/controller/ArticleLikeController.java
- src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
- src/main/java/com/example/lifeonhana/controller/ProductInsightController.java
- src/main/java/com/example/lifeonhana/dto/request/ProductInsightRequest.java
- src/main/java/com/example/lifeonhana/dto/response/ProductInsightResponse.java
- src/main/java/com/example/lifeonhana/repository/HistoryRepository.java
- src/main/java/com/example/lifeonhana/repository/ProductRepository.java
- src/main/java/com/example/lifeonhana/service/ProductInsightService.java
> ex) #이슈번호, #이슈번호
> 기사, 상품, 지출 내역, 마이데이터를 사용한 anthropic api 기반 상품 기대효과 생성 api 구현, swagger 설정
> JSON-159--feature/anthropicExpectation
> 계좌 이체(월급 채우기) api 구현
> [feat] 🦧 anthropic 기반 상품 기대효과 생성 api

- src/main/java/com/example/lifeonhana/controller/AccountController.java
- src/main/java/com/example/lifeonhana/dto/request/AccountTransferRequest.java
- src/main/java/com/example/lifeonhana/dto/response/AccountTransferResponse.java
- src/main/java/com/example/lifeonhana/entity/Account.java
- src/main/java/com/example/lifeonhana/global/exception/InsufficientBalanceException.java
- src/main/java/com/example/lifeonhana/repository/AccountRepository.java
- src/main/java/com/example/lifeonhana/service/AccountService.java
> #71 
> 계좌 이체 api 구현
> JSON-173--feature/accountTransfer
> 테스트코드 작성
> [feat] 🦧 계좌 이체 api 구현

- src/main/java/com/example/lifeonhana/controller/ArticleController.java
- src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
- src/main/java/com/example/lifeonhana/dto/response/ArticleSearchResponseDTO.java
- src/main/java/com/example/lifeonhana/dto/response/ProductListResponseDTO.java
- src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
- src/main/java/com/example/lifeonhana/repository/ProductRepository.java
- src/main/java/com/example/lifeonhana/service/ArticleService.java
- src/main/java/com/example/lifeonhana/service/ProductLikeService.java
- src/main/java/com/example/lifeonhana/service/ProductService.java
#70 
- page 구현 부분을 무한스크롤로 변경
- `Json 193  refactor/slice`
- 목돈 신청 api 마무리
> [feat] 🧚🏻‍♀️ 무한스크롤 구현

- src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
- src/main/java/com/example/lifeonhana/dto/response/ProductInsightResponse.java
- src/main/java/com/example/lifeonhana/entity/ProductLike.java
- src/main/java/com/example/lifeonhana/entity/ProductLikeId.java
- src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
- src/main/java/com/example/lifeonhana/service/ProductInsightService.java
- src/main/java/com/example/lifeonhana/service/ProductLikeService.java
> #74 
> 상품 좋아요 생성, 취소 기능 구현
상품의 기대효과 응답값에 좋아요 여부 추가
> JSON-195--feature/productLike
> 플라스크 서버 배포
> [feat] 🦧 상품 좋아요 생성, 취소 api && 기대효과 응답에 좋아요 여부 추가

- src/main/java/com/example/lifeonhana/controller/LumpSumController.java
- src/main/java/com/example/lifeonhana/dto/request/LumpSumRequestDTO.java
- src/main/java/com/example/lifeonhana/dto/response/LumpSumResponseDTO.java
- src/main/java/com/example/lifeonhana/entity/LumpSum.java
- src/main/java/com/example/lifeonhana/repository/AccountRepository.java
- src/main/java/com/example/lifeonhana/repository/LumpSumRepository.java
- src/main/java/com/example/lifeonhana/repository/WalletRepository.java
- src/main/java/com/example/lifeonhana/service/LumpSumService.java
- src/main/java/com/example/lifeonhana/service/WalletService.java
- #69 
- 목돈 신청 api 구현
- 신청후 바로 계좌에서 돈이 빠져나가는 방식
- `JSON-194--feature/lumpsum`
- 상품 상세 응답 수정
> [feat] 🧚🏻‍♀️목돈 신청 api #69

- src/main/java/com/example/lifeonhana/dto/response/AccountResponseDTO.java
- src/main/java/com/example/lifeonhana/service/AccountService.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 현재 작업중인 브랜치를 적어주세요
> 다음 작업 계획 간단히
> [fix] 🦧 계좌 목록 반환 값에 id 추가

- src/main/java/com/example/lifeonhana/dto/response/LifeProductResponseDTO.java
- src/main/java/com/example/lifeonhana/dto/response/LoanProductDetailResponseDTO.java
- src/main/java/com/example/lifeonhana/dto/response/SavingProductResponseDTO.java
- src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
- src/main/java/com/example/lifeonhana/service/ProductService.java
- #77 
- 대출, 예적금, 라이프 각 상품별로 좋아요 여부 보내도록 api 수정하였습니다.
- `JSON-197--refactor/products`
- 서버
> [refactor] 🧚🏻‍♀️ 상품 상세 좋아요 여부 추가 #77

- src/main/java/com/example/lifeonhana/dto/response/UserResponseDTO.java
- src/main/java/com/example/lifeonhana/service/UserService.java
> [fix] 🦥 사용자 정보 수정

- src/main/java/com/example/lifeonhana/dto/response/AuthResponseDTO.java
- src/main/java/com/example/lifeonhana/service/AuthService.java
- src/main/resources/application.yml
- src/test/java/com/example/lifeonhana/auth/AuthIntegrationTest.java
- src/test/java/com/example/lifeonhana/auth/AuthServiceTest.java
- src/test/java/com/example/lifeonhana/history/HistoryIntegrationTest.java
> ex) #81 
>최초로그인 관리 수정
> JSON-199--fix/signin
> 다음 작업 계획 간단히
> [fix] 최초로그인 관리 수정 #81

- build.gradle
- src/main/java/com/example/lifeonhana/client/RecommendationClient.java
- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- src/main/java/com/example/lifeonhana/controller/WhilickController.java
- src/main/java/com/example/lifeonhana/dto/response/PageableDTO.java
- src/main/java/com/example/lifeonhana/dto/response/WhilickContentDTO.java
- src/main/java/com/example/lifeonhana/dto/response/WhilickResponseDTO.java
- src/main/java/com/example/lifeonhana/dto/response/WhilickTextDTO.java
- src/main/java/com/example/lifeonhana/entity/Whilick.java
- src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
- src/main/java/com/example/lifeonhana/repository/WhilickRepository.java
- src/main/java/com/example/lifeonhana/service/WhilickService.java
> #45 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
Json-160--feature/whilick
> 다음 작업 계획 간단히
> [feat] 🐢 휘릭 api 구현

- src/main/java/com/example/lifeonhana/client/RecommendationClient.java
- src/main/java/com/example/lifeonhana/controller/AuthController.java
- src/main/java/com/example/lifeonhana/dto/request/AuthRequestDTO.java
- src/main/java/com/example/lifeonhana/dto/request/RefreshTokenRequestDTO.java
- src/main/java/com/example/lifeonhana/dto/response/AuthResponseDTO.java
- src/main/java/com/example/lifeonhana/service/AuthService.java
- src/test/java/com/example/lifeonhana/auth/AuthIntegrationTest.java
- src/test/java/com/example/lifeonhana/auth/AuthServiceTest.java
#88
auth dto record 수정 
JSON-209--fix/auth
> 다음 작업 계획 간단히
> [fix] 🐢 auth dto record 로 수정 #88

- src/main/java/com/example/lifeonhana/client/RecommendationClient.java
- src/main/java/com/example/lifeonhana/controller/WhilickController.java
- src/main/java/com/example/lifeonhana/repository/WhilickRepository.java
- src/main/java/com/example/lifeonhana/service/WhilickService.java
> #88 
> recommendation url 변경
> JSON-207--fix/whilick
> 다음 작업 계획 간단히
> 🐢 recommendation url 변경

- src/main/java/com/example/lifeonhana/service/WalletService.java
- #93
- 응답메세지 형식 수정
- `JSON-214--fix/wallet`
- 스웨거 수정
> [fix] 🧚🏻‍♀️하나지갑 응답보내주는 형식 수정 #93

- src/main/java/com/example/lifeonhana/client/RecommendationClient.java
- src/main/resources/application.yml
> #87
> 테스트 db 연결, recommend 예외처리
> 다음 작업 계획 간단히
> [fix] 🐢 테스트 db 연결, recommend 예외처리

- src/main/java/com/example/lifeonhana/controller/HistoryController.java
- src/main/java/com/example/lifeonhana/dto/response/HistoryResponseDTO.java
- src/main/java/com/example/lifeonhana/repository/HistoryRepository.java
- src/main/java/com/example/lifeonhana/service/HistoryService.java
> #96
> history slice 적용, 날짜 형식 수정
> JSON-217--fix/history
> 다음 작업 계획 간단히
> [fix] 🐢 history slice 적용, 날짜 형식 수정

- src/main/java/com/example/lifeonhana/controller/LumpSumController.java
- src/main/java/com/example/lifeonhana/dto/request/LumpSumRequestDTO.java
- src/main/java/com/example/lifeonhana/dto/request/WalletRequestDTO.java
- src/main/java/com/example/lifeonhana/dto/response/LumpSumResponseDTO.java
- src/main/java/com/example/lifeonhana/global/exception/BadRequestException.java
- src/main/java/com/example/lifeonhana/global/exception/BaseException.java
- src/main/java/com/example/lifeonhana/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/lifeonhana/repository/WalletRepository.java
- src/main/java/com/example/lifeonhana/service/LumpSumService.java
- #97 
- 목돈 신청시 요청으로 들어온 계좌에서 하나지갑으로 금액 보내기
- `JSON-219--fix/lumpsum`
리얼 테스트코드 작성
> [fix] 🧚🏻‍♀️ 목돈신청 변경

- src/main/java/com/example/lifeonhana/controller/ArticleController.java
- src/test/java/com/example/lifeonhana/controller/ArticleControllerTest.java
> ex) #102 
> article 테스트 코드 작성
> JSON-223--test/article
> articleLikex테스트코드
> [test] 🦥 article 테스트 코드 작성

- src/test/java/com/example/lifeonhana/controller/ArticleLikeControllerTest.java
> ex) #105 
>  articleLike 테스트 코드 작성
>JSON-224-test/atilcleLike 
> productLike 테스트 코드 작성
> [test] 🦥 articleLike 테스트 코드 작성

- src/main/java/com/example/lifeonhana/controller/ProductInsightController.java
- src/main/java/com/example/lifeonhana/service/ProductInsightService.java
- src/test/java/com/example/lifeonhana/productInsight/ProductInsightControllerTest.java
- src/test/resources/application-test.yml
> #107 
> productInsight 테스트코드 작성
> JSON-215-test/anthropicEffect
> LoanRecommendation 테스트 코드 작성
> [test] 🦧 productInsight 테스트코드 작성

- src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
- src/main/java/com/example/lifeonhana/service/LoanRecommendationService.java
- src/test/java/com/example/lifeonhana/controller/LoanRecommendationControllerTest.java
- src/test/java/com/example/lifeonhana/controller/ProductInsightControllerTest.java
> #109 
> LoanRecommendationController 테스트 코드 작성
> JSON-226-test/loanRecommendation
> 다음 작업 계획 간단히
> [test] 🦧 LoanRecommendationController 테스트 코드 작성

- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- src/main/java/com/example/lifeonhana/controller/HistoryController.java
- src/main/java/com/example/lifeonhana/filter/JwtAuthenticationFilter.java
- src/main/java/com/example/lifeonhana/service/AuthService.java
- src/test/java/com/example/lifeonhana/controller/AuthControllerTest.java
- src/test/java/com/example/lifeonhana/controller/HistoryControllerTest.java
- src/test/java/com/example/lifeonhana/history/HistoryIntegrationTest.java
- src/test/java/com/example/lifeonhana/jwt/JwtAuthenticationFilterTest.java
- src/test/java/com/example/lifeonhana/service/AuthServiceTest.java
- src/test/java/com/example/lifeonhana/service/JwtServiceTest.java
- src/test/java/com/example/lifeonhana/service/RedisServiceTest.java
> #100 
> history 테스트 코드 추가, auth 테스트 코드 수정, filter 수정
> JSON-220--test/history
> 다음 작업 계획 간단히
> [test] 🐢 history 테스트코드 추가

- src/test/java/com/example/lifeonhana/controller/ArticleLikeControllerTest.java
- src/test/java/com/example/lifeonhana/controller/ProductLikeControllerTest.java
> hot fix
> 토큰 관련 테스트 코드 수정
> 다음 작업 계획 간단히
> [fix] 🐢 토큰 관련 테스트 코드 수정

- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- #117 
- cors 설정 추가 및 samesite 설정
- `JSON-222--fix/cors`
- 백엔드 url 앞에 /api 추가
- 추후 회의 한번 더 하는것으로,, 
- 테스트코드
> [fix] 🧚🏻‍♀️cors 설정 추가 및 samesite 설정 #117

- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- src/main/resources/application.yml
- #117 
- 백엔드 모든 경로 앞에 /api 추가
- `JSON-198--hotfix`
- 테스트코드
> [hotfix] 🧚🏻‍♀️백엔드 경로 /api 추가 #117

- src/test/java/com/example/lifeonhana/controller/LumpSumControllerTest.java
#119
- lumpsum controller 테스트코드 작성
- `JSON-228-test/Lumpsum`
- lumpsum controller의 경우 분기가 없어서 따로 branch coverage는 채우지 않았습니다! 
- product test code
> [test] 🧚🏻‍♀️lumpsum controller test code #119

- src/test/java/com/example/lifeonhana/controller/UserControllerTest.java
> #115 
> User 테스트 코드 작성
> JSON-227--test/user
> 다음 작업 계획 간단히
> [test] 🐢 User 테스트 코드 작성 #115

- src/test/java/com/example/lifeonhana/controller/WhilickControllerTest.java
> #125
> whilickController 테스트 코드 작성 
> JSON-231--test/whilick
> 다음 작업 계획 간단히
> [test] 🐢 whilickController 테스트 코드 작성 #125

- src/test/java/com/example/lifeonhana/controller/LumpSumControllerTest.java
- src/test/java/com/example/lifeonhana/controller/ProductControllerTest.java
- #120 
- #119 
- product controller 작성
- lumpsum controller 수정
- `JSON-229-test/product`
- wallet 테스트코드
> [test] 🧚🏻‍♀️ product controller

- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- src/main/resources/application.yml
- src/test/java/com/example/lifeonhana/controller/WalletControllerTest.java
- #121 
- wallet controller test doce 
- `JSON-230--test/wallet`
- yml , security config에서 일부 경로 변경
- 테스트코드 보완
> [test] 🧚🏻‍♀️Wallet controller test code #121

- build.gradle
- src/main/java/com/example/lifeonhana/repository/AccountRepository.java
- src/main/java/com/example/lifeonhana/service/AccountService.java
- src/main/resources/application.yml
>  #129 
> actuator설정&&이자 지급 기능 추가
> JSON-196--feature/actuator
> 다음 작업 계획 간단히
> [feat] 🦥 actuator설정&&이자 지급 기능 추가

- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
- src/main/java/com/example/lifeonhana/controller/ArticleController.java
> ex) #84 
> security config 에 lifeonhana.topician 추가, articlecontroller 스웨거 빠진 부분 추가
> JSON-218--fix/swagger
> 다음 작업 계획 간단히
> [fix] 🐢 swagger 수정 #84

- src/main/java/com/example/lifeonhana/repository/WhilickRepository.java
- src/main/java/com/example/lifeonhana/service/WhilickService.java
> #134  
> 휘릭 오류 수정
>  JSON-198--hotfix
> 다음 작업 계획 간단히
> [fix] 🐢 휘릭 오류 수정 #134

- src/main/java/com/example/lifeonhana/config/SecurityConfig.java
> #136
> cors 설정 추가
> 다음 작업 계획 간단히
> [chore] 🐢 cors 설정 추가

- src/main/java/com/example/lifeonhana/service/ArticleService.java
> #142 
> 오류 수정
> JSON-252-hotfix/getArticleDetails
> [fix] 🦧 컬럼 상세 조회 오류 수정

- src/main/java/com/example/lifeonhana/entity/Wallet.java
- src/main/java/com/example/lifeonhana/repository/WalletRepository.java
- src/main/java/com/example/lifeonhana/service/LumpSumService.java
- #141 
- 하나지갑 잔액 추가
- `JSON-256--fix/wallet`
- 서버 리팩토링
> [fix] 🧚🏻‍♀️wallet balance 추가

- src/main/java/com/example/lifeonhana/service/LumpSumService.java
- src/main/java/com/example/lifeonhana/service/WalletService.java
- #141 
- 현재 월급에서 목돈신청시 잔액 계속 쌓이도록 수정
- `fix/wallet`
- 서버 빌드
> [fix] 🧚🏻‍♀️wallet balance 수정

- src/main/java/com/example/lifeonhana/service/WalletService.java
#141 
- 월급 변경시 하나지갑 금액 초기화되는것 수정
- 현재 작업중인 브랜치를 적어주세요
- 서버 리팩토링
> [fix] 🧚🏻‍♀️wallet balance 수정 

- src/main/java/com/example/lifeonhana/controller/HistoryController.java
- src/main/java/com/example/lifeonhana/controller/WhilickController.java
- src/main/java/com/example/lifeonhana/service/HistoryService.java
- src/main/java/com/example/lifeonhana/service/WhilickService.java
- src/test/java/com/example/lifeonhana/controller/HistoryControllerTest.java
- src/test/java/com/example/lifeonhana/controller/WhilickControllerTest.java
> 
> whilick user id 받는 방식 수정
> 다음 작업 계획 간단히
> [fix] 🐢 whilick user id 받는 방식 수정

- src/test/java/com/example/lifeonhana/controller/UserControllerTest.java
> 
> user controller test 수정
> 다음 작업 계획 간단히
> [fix] 🐢 user controller test 수정

- src/main/java/com/example/lifeonhana/dto/response/LifeProductResponseDTO.java
- src/main/java/com/example/lifeonhana/dto/response/LoanProductDetailResponseDTO.java
- src/main/java/com/example/lifeonhana/dto/response/SavingProductResponseDTO.java
- src/test/java/com/example/lifeonhana/controller/ProductControllerTest.java
> product 에서 islike -> isliked 로 수정
> Json-198--hotfix
> 다음 작업 계획 간단히
> [fix] 🐢 productcontroller 테스트 코드 수정

- src/main/java/com/example/lifeonhana/service/LumpSumService.java
- src/test/java/com/example/lifeonhana/controller/ProductControllerTest.java
- #153 
- 입출금 내역에 목돈 지급 내역 추가
- product controller 테스트 수정
- `JSON-263--feature/lumpsum`
> 다음 작업 계획 간단히
> [feat] 🧚🏻‍♀️ 입출금 내역 목돈 지급 추가

- src/main/java/com/example/lifeonhana/config/SwaggerConfig.java
- src/main/java/com/example/lifeonhana/controller/AccountController.java
- src/main/java/com/example/lifeonhana/controller/ArticleController.java
- src/main/java/com/example/lifeonhana/controller/ArticleLikeController.java
- src/main/java/com/example/lifeonhana/controller/AuthController.java
- src/main/java/com/example/lifeonhana/controller/HistoryController.java
- src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
- src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
- src/main/java/com/example/lifeonhana/controller/WhilickController.java
- src/test/java/com/example/lifeonhana/controller/ArticleLikeControllerTest.java
> #159 
> swagger 수정
> JSON-267--fix/swagger
> 다음 작업 계획 간단히
> [fix] 🐢 swagger 수정 #159

- README.md
- src/main/java/com/example/lifeonhana/config/SwaggerConfig.java
- src/main/java/com/example/lifeonhana/controller/AccountController.java
- src/main/java/com/example/lifeonhana/controller/ArticleController.java
- src/main/java/com/example/lifeonhana/controller/ArticleLikeController.java
- src/main/java/com/example/lifeonhana/controller/AuthController.java
- src/main/java/com/example/lifeonhana/controller/HistoryController.java
- src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
- src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
- src/main/java/com/example/lifeonhana/controller/WhilickController.java
- src/test/java/com/example/lifeonhana/controller/ArticleLikeControllerTest.java
- 테스트 코드 수정
- swagger 수정
- `JSON-41--develop`
> [release] 🪄 Version 0.1.1
